version: "3.9"
services:
  python:
    container_name: selenium_python
    build: ./python
    volumes:
      - ../:/app
    environment: 
      SELENIUM_URL: http://selenium:4444/wd/hub
    tty: true
  selenium:
    image: selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210823
    container_name: chrome
    ports:
      - 4444
      - 5900:5900
    volumes: 
      - /dev/shm:/dev/shm